### ISSUE TITLE
i2c errors on NanoPi Neo

### ISSUE THREAD

**Issue by irunonayran** [YunoHost-Apps/netdata_ynh#10]
If I use it on NanoPi Neo running ARMBIAN 5.31 stable Debian GNU/Linux 8 (jessie) 3.4.113-sun8i, I get the following error message printed to log in fast succession
```
[   11.210906] twi_start()434 - [i2c0] START can't sendout!
[   11.221376] twi_start()434 - [i2c0] START can't sendout!
[   11.228399] twi_start()434 - [i2c0] START can't sendout!
[   11.237229] twi_start()434 - [i2c0] START can't sendout!
```
and the logfile fills up my disk
Any idea how to avoid this?

**Comment by JimboJoe** [comment]
Unfortunately I have no idea... It doesn't seem to be a known problem in the netdata application, and when searching generally for this error on the Internet, it seems quite often linked to your hardware model. Maybe a later kernel fix...?

**Comment by irunonayran** [comment]
Ok, I switched to mainline (4.11.5) and have no problems so far. Thanks
