### ISSUE TITLE
Use netdata upgrade script

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/netdata_ynh#12]
Hi, I use YUnohost netdata instance as my master instance, but, the default install use git upgrade script but not the YUnohost's one.

This led to this issue for me: https://github.com/firehol/netdata/issues/2934#issuecomment-340173792

Best regards.

**Comment by Christophe31** [comment]
Is there any way to use both netdata with yunohost authentication and graphite with slave servers using default upgrade procedure (crontab syncing code to master)

**Comment by JimboJoe** [comment]
As all your instances are not installed via YunoHost, you need to keep your netdata instances versions in-sync by yourself...
In this case, the YunoHost package is maybe not the best solution for you: you could try installing netdata via git "by hand", and use the [redirect app](https://github.com/YunoHost-Apps/redirect_ynh) to create the portal entry in YunoHost.

**Comment by Christophe31** [comment]
If I do so I also need to setup graphite data input integration, uhm, it's not the answer I expected but, my usecase must not be so common.

**Comment by JimboJoe** [comment]
Well, you have installed graphite on your own, haven't you? Configuring the NetData backend is not that difficult, there are only [a couple of parameters to set](https://github.com/firehol/netdata/wiki/netdata-backends).

**Comment by Christophe31** [comment]
nope, I use the one provided by yunohost.

**Comment by JimboJoe** [comment]
Hmm... YunoHost only provides glances. Maybe you use the grafana package (that I made) that installs influxdb and configures an opentsdb backend for netdata...?

**Comment by Christophe31** [comment]
yes, sorry, I mixed names ^^.

**Comment by JimboJoe** [comment]
Closing as it looks exclusively related to your specific context and not to that YunoHost app. Feel free to reopen if needed 😉
