### ISSUE TITLE
Default install should only be accessible to one user (admin)

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/netdata_ynh#13]
It would be nicer for netdata to ask which user should access the data when installing it, instead of showing the app to all users.

**Comment by arthurlogilab** [comment]
Hey, thanks for the prompt change ! 

I've added a few comments to the patch. 

Another question : will notification emails only be sent to the users that have access or to an admin, or to all users ? (should I open a different issue for this ?)

**Comment by JimboJoe** [comment]
Thanks for your feedback!
Notifications are sent by default to root user, and this alias is attributed by default to the first user created in YunoHost.
It can be changed later in `/opt/netdata/etc/netdata/health_alarm_notify.conf`.
