### ISSUE TITLE
[privacy] disable registry by default

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/netdata_ynh#14]
When you open netdata in your browser by default it "pings" https://registry.my-netdata.io so that you can navigate accros multiple netdata instances through the top left menu. 

Here is some info about what is being "shared"/"leaked" to my-netdata :  https://github.com/firehol/netdata/wiki/mynetdata-menu-item

To disable you can set [registry].enabled to no. But you can also get it to point to itself : 
https://github.com/firehol/netdata/wiki/mynetdata-menu-item#every-netdata-can-be-a-registry

**Comment by JimboJoe** [comment]
Fixed by https://github.com/YunoHost-Apps/netdata_ynh/commit/07b42d219a9231eccc608952063d6b4f24c32ca8
