### ISSUE TITLE
Badges in readme.md link to Piwigo app

### ISSUE THREAD

**Issue by Sekanato** [YunoHost-Apps/netdata_ynh#16]
Install badge links to – `https://install-app.yunohost.org/?app=piwigo`
Integration level badge links to – `https://ci-apps.yunohost.org/jenkins/job/piwigo%20%28Community%29/lastBuild/consoleFull` This one even throws 404.

Pretty sure the first one should go to `https://install-app.yunohost.org/?app=netdata` 
And the second one to `https://ci-apps.yunohost.org/jenkins/job/netdata%20(Community)/lastBuild/`

First couple of times clicking the install badge was pretty confusing :smile:

**Comment by JimboJoe** [comment]
Thanks for reporting that! :wink:
