### ISSUE TITLE
Your app is out of date on the community list

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/netdata_ynh#17]
Hello,

The [community list](https://github.com/YunoHost/apps/blob/master/community.json) uses an old commit for your app.
Since your app has some corrections, would you please update the community list if possible.

For the Apps group.

**Comment by JimboJoe** [comment]
You're totally right!
I just approved this PR https://github.com/YunoHost/apps/pull/436 and will post in the forum as soon as it gets merged :+1:
