### ISSUE TITLE
ispublic needed?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/netdata_ynh#2]
As this app is about internal monitoring, is it really needed to allow the app to be public?
Having the choice in the manifest is fine but personally I prefer not to give the choice for apps that are not meant to be public (like phpmyadmin). This eases the install process especially for non-expert users

**Comment by JimboJoe** [comment]
I think there is no such security issue as exposing phpmyadmin as public: you can't modify anything from NetData interface (yet of course we depend on security flaws).
As application is private by default, and as there may be rare occasions people would want to make it public, I prefer to let the choice by now.
This question should be anyway definitely discussed in the Apps Group to define a "global" policy on this point ;-)
