### ISSUE TITLE
Can't disable the mail alarms

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/netdata_ynh#23]
Hello,

I have set some alarm to «silent», but despite that, it still send me errors emails.

**Comment by JimboJoe** [comment]
I've never used that option...
Maybe you could look for help with the netdata project?
For example, an issue that seems related [here](https://github.com/netdata/netdata/issues/3803).

**Comment by stemy2** [comment]
Thanks hfor the tip, but even after restart, i still receive the emails.

**Comment by stemy2** [comment]
I found a solution: i changed the parameter SEND_EMAIL to «NO». Now i don't receive anything.
