### ISSUE TITLE
Error when uninstalling

### ISSUE THREAD

**Issue by Jojo144** [YunoHost-Apps/netdata_ynh#30]
I got an error during the uninstallation (launched from `sudo yunohost app remove netdata`):

```
Warning: ./netdata-uninstaller.sh: line 12: installer/functions.sh: No such file or directory
Warning: E: Unable to locate package netdata-deps
Success! netdata has been removed
Success! The SSOwat configuration has been generated
```

The application does not appear in Yunohost anymore. But it is still running, sending mails, ...

I can provide more information if you say me where to find them.

**Comment by JimboJoe** [comment]
As recommended [here](https://docs.netdata.cloud/packaging/installer/uninstall/), can you try:
```
wget https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
chmod +x ./netdata-uninstaller.sh
./netdata-uninstaller.sh --yes --env /opt/netdata/etc/netdata/.environment
```

**Comment by Jojo144** [comment]
Thank you very much. I was not able to do this because the .environment file was deleted.
For the moment I just reinstalled the app (and it works!).
I don't know what version it was, I believe that I installed it in January (2019) ...

**Comment by alexAubin** [comment]
Closing because issue is superold, package probably got refactored a couple time since then
