### ISSUE TITLE
Failed to get status information via dbus for service netdata, systemctl didn't recognize this service ('NoSuchUnit').

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/netdata_ynh#35]
Hello,
I have the same problem as exposed there by someone else : 
https://forum.yunohost.org/t/probleme-apres-la-desinstallation-de-netdata/8187

Even after I removed netdata, the YunoHost admin panel find the netdata service but can't do anything with it.

Is there a way to properly remove this ?

**Comment by JimboJoe** [comment]
Does `yunohost service remove netdata` fixes it?

**Comment by supermamie** [comment]
It seems so 🙂
I'll answer on the forum, thanks a lot.
