### ISSUE TITLE
Cloud Support

### ISSUE THREAD

**Issue by underhood** [YunoHost-Apps/netdata_ynh#52]
Hi,

had a question posted on the community forum https://community.netdata.cloud/t/no-cloud-monitoring-anymore/525 about cloud support.

May I ask the reason why the Cloud is disabled? Is it technical problem or another "philosophical" issue?

In case of technical issue can you provide any details? Are we able to help you to solve it?

Thank you

**Comment by JimboJoe** [comment]
Hi,
It's clearly not a technical problem, only a philosophical choice: YunoHost is aiming at contributing to the web decentralization as well as data privacy, so it seemed to me that having this option disabled by default was the right decision.
Adding the choice for cloud activation could certainly be considered. Please feel free to propose a PR for this and I'll help you get that integrated 👍

**Comment by underhood** [comment]
Hi,

thanks for the answer, we have had issues with building Cloud features on certain systems/platforms. I certainly do understand and agree and strongly applaud your philosophy of protecting privacy and data of users :+1:.

I would like to point out that with telemetry disabled agent with cloud features enabled will never send any data unless you as a user claim the node. Additionally cloud can also be disabled by configuration.

I will let you however to decide :). In case you need any help for this or other issues you might have with Netdata please let us know.

**Comment by underhood** [comment]
Also quick comment about centralisation. I would like to point out Netdata Cloud is not storing the actual metrics data at all. We just stream them from agent to browser (Cloud is basically acting as a proxy). We do store metadata (list of charts etc.) which are functionally necessary.  All that again only if user manually Claims a node. No connection to Cloud is made until you claim.
