### ISSUE TITLE
Provide example of yunohost_admin.conf

### ISSUE THREAD

**Issue by sgvj** [YunoHost-Apps/netdata_ynh#7]
Upon adding the following to either the port 80 server or 443
```
     location /stub_status {
         stub_status;
     }
```
I get the error:
> invalid number of arguments in "stub_status" directive in /etc/nginx/conf.d/yunohost_admin.conf:1

Can you provide an example of your config?
Thanks so much for making this, otherwise works just great!

**Comment by JimboJoe** [comment]
Here is the configuration I added:
```
location /stub_status {
  stub_status on;
  # Security: Only allow access from the IP below.
  allow 127.0.0.1;
  # Deny anyone else
  deny all;
 }
```
Your error message is caused by the missing `on` parameter.
