### ISSUE TITLE
Last upgrade broke my YNH admin interface

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/netdata_ynh#85]
### Describe the bug

Since i upgraded netdata, i can't access to the admin interface. I juste habve the message: **File does not exist, or is not accessible: /opt/netdata/usr/share/netdata/web/yunohost/admin/**. If i delete netdata, i have an HTTP 502 error.

### Context

- Hardware: *Desktop PC*
- YunoHost version: 4.3.6.3
- I have access to my server: *SSH only*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: 
- If upgrading, current package version: *1.35.1~ynh1*

### Steps to reproduce

    sudo yunohost app upgrade

### Expected behavior

Upgrade

### Logs

https://paste.yunohost.org/raw/elozivusaz
https://paste.yunohost.org/raw/yudatecife

**Comment by JimboJoe** [comment]
Is your netdata instance at a domain root? If so, could you please check you have the netdata.conf nginx conf file netdata.conf in /etc/nginx/conf.d/domain.conf.d, and potentially a duplicate in /etc/nginx/conf.d/yourfdefaultdomain.conf.d?
If so, could you remove the latter one and reload nginx (systemctl reload nginx)?

**Comment by stemy2** [comment]
The directory "/etc/nginx/conf.d/mydefaultdomain.tld.conf.d" is empty.

I deleted the one contained in "/etc/nginx/conf.d/domain.conf.d" then reloaded nginx, no changes.

**Comment by JimboJoe** [comment]
Sorry; I misled you: you have to replace "domain" by the domain where you installed netdata (at the root "/" or not?).
"mydefaultdomain" is the default domain of your YunoHost install (where you access the sso or the admin interface). Is it really empty?
Now that you've removed the netdata.conf of the "domain" conf directory, is there any remaining? If so, you need to keep it, but in the right directory corresponding to the domain where you installed netdata.

**Comment by stemy2** [comment]
```
Sorry; I misled you: you have to replace "domain" by the domain where you installed netdata (at the root "/" or not?).
"mydefaultdomain" is the default domain of your YunoHost install (where you access the sso or the admin interface). Is it really empty?
```
No, it didn't misleaded me, i understood i had to replace them by actual (sub)domains.

**Comment by JimboJoe** [comment]
OK, good 😅 
So what is the status? Is netdata installed at the root of the domain? Do you have any remaining netdata.conf file in the nginx conf directories?
(For the background, it happened to me once when I tested the upgrade, to have a duplicate netdata.conf file in the conf dir of my default YunoHost domain, and it created the same symptoms... Yet I don't understand (yet) that behavior... 😅).

**Comment by stemy2** [comment]
Ok, i reinstalled netdata and applied what you said and it's working now.

Thanks.
