### ISSUE TITLE
netdata broke the admin panel of ynh

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/netdata_ynh#87]
### Describe the bug

After I updated netdata to latest package version (version: `1.35.1~ynh1`), the admin web panel of ynh became inaccessible and returns me:
`File does not exist, or is not accessible: /opt/netdata/usr/share/netdata/web/yunohost/admin/`

### Context

- Hardware: *Selfhosted virtual machine*
- YunoHost version: 
```sh
yunohost tools versions
yunohost:
  repo: stable
  version: 4.3.6.3
yunohost-admin:
  repo: testing
  version: 4.3.4.1
moulinette:
  repo: stable
  version: 4.3.3.1
ssowat:
  repo: stable
  version: 4.3.3.1
```
- I have access to my server: Through SSH & through the webadmin (& direct access via keyboard / screen if needed)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *master*
- If upgrading, current package version: *version: `1.35.1~ynh1`*

### Steps to reproduce

- *Upgrade netdata*
    ```sh
    yunohost app upgrade netdata
    ```
1. *Go to your admin panel*
2. *See error*

### Expected behavior

*Have access to the YNH administration interface*

### Logs

`/var/log/nginx/ynh-web-interface.tld-access.log` (nginx access log):
`192.168.x.x - - [10/Jul/2022:17:09:09 +0200] "GET /yunohost/admin/ HTTP/2.0" 404 107 "https://ynh-web-interface/yunohost/sso/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"`

**Comment by JimboJoe** [comment]
Duplicate of #85 
Please have a look at the manual corrective action (duplicate netdata.conf in another subdirectory of etc/nginx/conf.dd)

**Comment by OniriCorpe** [comment]
```bash
# find /etc/nginx/ -name "netdata.conf"
/etc/nginx/conf.d/ynh-web-interface.tld.d/netdata.conf
/etc/nginx/conf.d/netdata.example.tld.d/netdata.conf
# rm /etc/nginx/conf.d/yuno.emelyne.eu.d/netdata.conf
# service nginx reload
```

thanks it works! :)

**Comment by OniriCorpe** [comment]
```bash
# find /etc/nginx/ -name "netdata.conf"
/etc/nginx/conf.d/ynh-web-interface.tld.d/netdata.conf
/etc/nginx/conf.d/netdata.example.tld.d/netdata.conf
# rm /etc/nginx/conf.d/ynh-web-interface.tld.d/netdata.conf
# service nginx reload
```

thanks it works! :)
