### ISSUE TITLE
no auto restart on crash-shutdown.

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/netdata_ynh#9]
I got an exception which turned down netdata which closed it:

    22:24:50: netdata: INFO : Initializing file /opt/netdata/var/cache/netdata/UUID/net.vethd030791/sent.db.
    22:24:50: netdata: INFO : Initializing file /opt/netdata/var/cache/netdata/UUID/net_packets.vethd030791/main.db.
    22:24:50: netdata: ERROR: Cannot allocate PRIVATE ANONYMOUS memory for KSM for file '/opt/netdata/var/cache/netdata/UUID/net_packets.vethd030791/received.db'. (errno 12, Cannot allocate memory)
    22:24:50: netdata: ERROR: Cannot allocate PRIVATE ANONYMOUS memory for KSM for file '/opt/netdata/var/cache/netdata/UUID/net_packets.vethd030791/sent.db'. (errno 12, Cannot allocate memory)        
    22:24:50: netdata: FATAL: Cannot strdup() string 'sent' # : Cannot allocate memory

    22:24:50: netdata: INFO : Saving database [3 hosts(s)]...
    22:24:50: netdata: INFO : Saving database of host 'server_2_hostname'...
    22:24:50: netdata: INFO : IDLEJITTER thread exiting
    22:24:50: netdata: ERROR: STREAM server_hostname [receive from [anIP]:33516]: disconnected (completed updates 31608723).
    22:24:50: netdata: INFO : STREAM server_hostname [receive from [anIP]:33516]: receive thread ended (task id 22087)
    22:24:50: netdata: INFO : CGROUP thread exiting
    22:24:50: netdata: INFO : DISKSPACE thread exiting
    22:24:50: netdata: INFO : PROC thread exiting
    22:24:50: netdata: ERROR: PLUGINSD: plugin '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    22:24:50: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' on pid 6762 stopped after 632216 successful data collections (ENDs).
    22:24:50: netdata: ERROR: child pid 6762 killed by signal 15. (errno 9, Bad file descriptor)
    22:24:50: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' thread exiting
    22:24:50: netdata: INFO : PLUGINS.D thread exiting
    22:24:51: netdata: ERROR: PLUGINSD: plugin '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' disconnected.
    22:24:51: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' on pid 24107 stopped after 140782920 successful data collections (ENDs).
    22:24:51: netdata: ERROR: child pid 24107 killed by signal 15. (errno 9, Bad file descriptor)
    22:24:51: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' thread exiting
    22:24:51: netdata: ERROR: child pid 22828 killed by signal 13. (errno 9, Bad file descriptor)
    22:24:51: netdata: INFO : TC thread exiting
    22:24:55: netdata: INFO : Saving database of host 'server_hostname'...
    22:24:55: netdata: INFO : HEALTH thread exiting
    22:25:09: netdata: INFO : Saving database of host 'server_2_hostname'...
    22:26:31: netdata: INFO : netdata exiting. Bye bye...

but it didn't restarted. when I restarted it manually, it worked like a charm… shouldn't the service auto restart on unexpected shutdown?

**Comment by JimboJoe** [comment]
Well, that's an interesting question! There's no policy on this in the frame of YunoHost packaging rules.
At first, I would say we must align in priority with the original application. I've seen no discussion on this on the NetData bugtracker.

Technically, it could be doable quite simply with the Restart/RestartSec parameters in the systemd service definition (which is created by the upstream NetData installer). But before doing that at the YunoHost package level, I'd prefer to open that discussion with the NetData developers to see if it would be wiser that they implement it in NetData itself. Maybe you could open an issue on NetData bugtracker, @Christophe31... ?

P.S. : As for your stopping cause, you seem to have had a serious memory issue...

**Comment by Christophe31** [comment]
Memory issue? you mean memory integrity? I get the net data streaming from external servers, one of those servers may have had memory space issue but not the YunoHost's one.
I opened an Issue there( https://github.com/firehol/netdata/issues/2617 ), and Thanx for the tip.

**Comment by JimboJoe** [comment]
When I see:
```
22:24:50: netdata: FATAL: Cannot strdup() string 'sent' # : Cannot allocate memory
```
I feel your server was in very bad shape at that time 😉 
Thanks for the upstream issue!

**Comment by JimboJoe** [comment]
OK, I've seen that your [upstream issue](https://github.com/firehol/netdata/issues/2617) got coded by @ktsaou, which is great!
So, this issue should be fixed when integrating future NetData version.
Thanks for your contribution!

**Comment by JimboJoe** [comment]
Now fixed by upstream version.
